name: CI-S02
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Versões
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
    - run: node -v
    - run: npm -v
  
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: michelleamesquita/sast:latest
    steps:
      - uses: actions/checkout@v3
      - name: Testes
        uses: docker://michelleamesquita/sast:latest
        with:
          options: -v $PWD/:/app
          args: -d=./app/ -l=node.js
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"
          
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: echo "Terminou =)"
