name: CI-S02
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
    - run: node -v
    - run: npm -v
    - run: sudo apt-get install firefox
    - run: firefox --version
  
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qy --no-install-recommends install xvfb
      - run: set -e
      - run: echo "Starting X virtual framebuffer (Xvfb) in background..."
      - run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
      - run: export DISPLAY=:10.0
      - run: exec "$@"
      - run: firefox https://projeto-web-sorteio.netlify.app
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"
          
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Terminou =), será que vc acertou o número? =D"
