name: CI-S02
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checando versões
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
    - run: node -v
    - run: npm -v
  
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: michelleamesquita/sast:latest
    steps:
      - name: Teste AppThreat
      - uses: actions/checkout@v3
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"
      - name: Teste SAST
        uses: docker://michelleamesquita/sast:latest
        with:
          options: -v $PWD/:/app
          args: -d=./app/ -l=nodejs
          
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Acessando o Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Finalizando
      - uses: actions/checkout@v3
      - run: echo "Terminou =)"
