name: Somativa02 LHP VSB
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checando versões
      uses: actions/checkout@v3
    - name: Preparando...
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
    - name: Checando Node
      run: node -v
    - name: Checando NPM
      run: npm -v
