name: DevOps Somativa02 LHP VSB
on: push
jobs:
  build-node:
    name: Build
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
