name: Somativa02 LHP VSB
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checando versões
        uses: actions/checkout@v3
      - name: Preparando...
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
      - name: Checando Node
        run: node -v
      - name: Checando NPM
        run: npm -v

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: michelleamesquita/sast:latest
    steps:
      - name: Realizando testes
        uses: actions/checkout@v3
      - name: Início SAST
        uses: docker://michelleamesquita/sast:latest
        with:
          options: -v $PWD/:/app
          args: -d=./app/ -l=node.js
      - name: Início AppThreat
        uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"

  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Subindo aplicação
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Preparando Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build e push do projeto
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: luishpaiva/webapp:latest, luishpaiva/webapp:${{ github.run_number }}
      - name: Finalizando
        run: echo "Pipeline finalizado com sucesso =)"
