name: DevOps Somativa02 LHP VSB
on: push
jobs:
  build-node:
    name: Fase de Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: node --version
      - run: npm --version
